org: saikhanbileg
app: aws-node-http-api-project
service: aws-node-http-api-project
frameworkVersion: '3'
useDotenv: true

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs14.x
  environment:
    AWS_ACCESS_KEY_ID: ${env:AWS_ACCESS_KEY_ID}
    AWS_SECRET_ACCESS_KEY: ${env:AWS_SECRET_ACCESS_KEY}
    JWT_SECRET: ${env:JWT_SECRET}
    JWT_EXPIRESIN: ${env:JWT_EXPIRESIN}
    REGION: ${env:REGION}

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /{routeName}
          method: "*"
